"""Workfront semantics, over the in-house MCP estate.

D9: decided — we go through Chauncey's MCP (`chaunceyplum/mcp`), not Adobe's
official connector. Those Lambdas already authenticate via Workfront IMS, are
already deployed, and are already scoped per agent. Nothing here reaches
Workfront directly; `tap_mcp.py` owns the transport.

This file knows Workfront's object model and nothing about routing.

Object codes, confirmed against the tenant's real forms (config/workfront.yaml):
  OPTASK  issue / request   — "CSC Intake - Issue"
  PROJ    project           — "Campaign Brief", "CSC Campaign - Project"
  DOCU    document          — "CSC Asset - Document"
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

from agent_manager.gateway.adapters.tap_mcp import (
    McpToolError,
    McpUnavailable,
    TapMCP,
)
from agent_manager.gateway.adapters.tap_mcp import _cfg as wf_config

__all__ = [
    "Workfront",
    "WriteIntent",
    "McpUnavailable",
    "McpToolError",
    "form_by_role",
    "reconcile_fields",
]

# The tool families generated by make_crud_tools upstream. Every object gets
# _list, _get, _create, _update, _delete and _set_custom_fields.
OBJECT_TOOLS: dict[str, str] = {
    "OPTASK": "wf_core_issue",
    "PROJ": "wf_core_project",
    "TASK": "wf_core_task",
}


def form_by_role(role: str) -> dict[str, Any] | None:
    for f in wf_config().get("forms", []):
        if f.get("role") == role:
            return f
    return None


def reconcile_fields(object_code: str) -> list[str]:
    return wf_config().get("reconcile_fields", {}).get(object_code, ["ID", "name"])


@dataclass
class WriteIntent:
    """What we assert. Recorded before the call, compared after it."""

    object_code: str
    operation: str                      # create | update
    fields: dict[str, Any] = field(default_factory=dict)
    # DE: custom-form values. The record must already carry a categoryID
    # assigning the relevant custom form before these can be set.
    custom_fields: dict[str, Any] = field(default_factory=dict)
    form_id: str | None = None
    object_id: str | None = None

    @property
    def tool_prefix(self) -> str:
        try:
            return OBJECT_TOOLS[self.object_code]
        except KeyError:
            raise McpUnavailable(
                f"no tool family known for object code {self.object_code!r}"
            ) from None


class Workfront:
    def __init__(self, client: TapMCP | None = None):
        self.mcp = client or TapMCP()

    @property
    def configured(self) -> bool:
        return self.mcp.configured

    # ------------------------------------------------------------------ read

    def get(self, object_code: str, object_id: str, fields: list[str] | None = None) -> dict:
        tool = f"{OBJECT_TOOLS[object_code]}_get"
        args: dict[str, Any] = {"obj_id": object_id}
        names = fields or reconcile_fields(object_code)
        if names:
            args["fields"] = ",".join(names)
        result = self.mcp.call(tool, args)
        return _as_object(result)

    def list(self, object_code: str, name_contains: str | None = None, limit: int = 20) -> list[dict]:
        tool = f"{OBJECT_TOOLS[object_code]}_list"
        args: dict[str, Any] = {"limit": limit}
        if name_contains:
            args["name_contains"] = name_contains
        result = self.mcp.call(tool, args)
        if isinstance(result, dict):
            return result.get("data") or result.get("items") or []
        return result if isinstance(result, list) else []

    def comments(self, object_code: str, object_id: str) -> list[dict]:
        result = self.mcp.call(
            "wf_comments_list", {"obj_code": object_code, "obj_id": object_id}
        )
        if isinstance(result, dict):
            return result.get("data") or []
        return result if isinstance(result, list) else []

    # ----------------------------------------------------------------- write

    def create(self, intent: WriteIntent) -> dict:
        """Create an object, then apply its custom-form values.

        Two calls, deliberately: `_create` sets the native fields and the
        categoryID that assigns the custom form, and `_set_custom_fields`
        fills the DE: values. The record must carry the categoryID first —
        that ordering is the upstream tool's own stated requirement, not a
        preference.
        """
        fields = dict(intent.fields)
        if intent.form_id:
            fields.setdefault("categoryID", intent.form_id)

        created = _as_object(self.mcp.call(f"{intent.tool_prefix}_create", {"fields": fields}))
        object_id = str(created.get("ID") or created.get("id") or "")

        if intent.custom_fields and object_id:
            self.mcp.call(
                f"{intent.tool_prefix}_set_custom_fields",
                {"obj_id": object_id, "values": intent.custom_fields},
            )
            created = self.get(intent.object_code, object_id)
        return created

    def update(self, intent: WriteIntent) -> dict:
        if not intent.object_id:
            raise ValueError("update needs an object_id")
        updated = _as_object(
            self.mcp.call(
                f"{intent.tool_prefix}_update",
                {"obj_id": intent.object_id, "fields": intent.fields},
            )
        )
        if intent.custom_fields:
            self.mcp.call(
                f"{intent.tool_prefix}_set_custom_fields",
                {"obj_id": intent.object_id, "values": intent.custom_fields},
            )
            updated = self.get(intent.object_code, intent.object_id)
        return updated

    def post_comment(self, object_code: str, object_id: str, text: str) -> dict:
        """Agent 2's redraft channel — B2's `wf_comments_create`."""
        return _as_object(
            self.mcp.call(
                "wf_comments_create",
                {"obj_code": object_code, "obj_id": object_id, "text": text},
            )
        )

    # ------------------------------------------------------------ discovery

    def available_tools(self) -> list[str]:
        """What the estate actually exposes, for the whole Workfront surface."""
        names: list[str] = []
        for route in (
            "/mcp/workfront/core",
            "/mcp/workfront/comments",
            "/mcp/workfront/metadata",
            "/mcp/workfront/search",
        ):
            try:
                names.extend(t.get("name", "") for t in self.mcp.tools(route))
            except (McpUnavailable, McpToolError):
                continue
        return sorted(n for n in names if n)


def _as_object(result: Any) -> dict:
    """Workfront wraps single records in {"data": {...}}."""
    if isinstance(result, dict):
        inner = result.get("data")
        if isinstance(inner, dict):
            return inner
        return result
    return {}
